#include "gba.h"
#include "logic.h"
#include "draw.h"
#include "myLib.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/pacman.h"
#include "images/pacChar.h"
#include "images/gg.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    bool start_down = false;


    int pacRow = 85;
    int pacCol = 75;

    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the start state here.
                drawStartScreen();

                state = START_NODRAW;
                break;
            case START_NODRAW:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.

                if (KEY_DOWN(BUTTON_START, BUTTONS)) {
                    if (!start_down) {
                        state = APP_INIT;
                    }
                    start_down = true;
                } else {
                    start_down = false;
                }
                break;
            case APP_INIT:
                // Initialize the app. Switch to the APP state.
                initializeAppState(&currentAppState);

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

                // Wait for VBlank before we do any drawing.
                nextAppState.oldCharRow = pacRow;
                nextAppState.oldCharCol = pacCol;

                currentAppState.charRow = pacRow;
                currentAppState.charCol = pacCol;
                if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
                    if (pacCol > 1 && pacCol < 170) {
                        pacCol++;
                        nextAppState.charCol = pacCol;
                    }
                    if (pacCol >= 170) {
                        pacCol = pacCol - 1;
                        nextAppState.charCol = pacCol;
                    }
                }
                if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
                    if (pacCol > 1 && pacCol < 170) {
                        pacCol--;
                        nextAppState.charCol = pacCol;
                    }
                    if (pacCol <= 1) {
                        pacCol = pacCol + 1;
                        nextAppState.charCol = pacCol;
                    }
                }
                if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
                    if (pacRow > 1 && pacRow < 155) {
                        pacRow--;
                        nextAppState.charRow = pacRow;
                    }
                    if (pacRow <= 1) {
                        pacRow = pacRow + 1;
                        nextAppState.charRow = pacRow;
                    }
                }
                if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
                    if (pacRow > 1 && pacRow < 155) {
                        pacRow++;
                        nextAppState.charRow = pacRow;
                    }
                    if (pacRow >= 155) {
                        pacRow = pacRow - 1;
                        nextAppState.charRow = pacRow;
                    }
                }

                waitForVBlank();

                // Undraw the previous state
                undrawAppState(&currentAppState);

                // Draw the current state
                drawAppState(&nextAppState);

                // Now set the current state as the next state for the next iter.
                currentAppState = nextAppState;

                // Check if the app is exiting. If it is, then go to the exit state.
                if (nextAppState.gameOver) {
                    state = APP_EXIT;
                }

                if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
                    drawStartScreen();
                    state = START;
                }

                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the exit / gameover screen
                drawFullScreenImageDMA(gg);

                drawString(50, 30, "Press START to play again." , GREEN);

                drawString(90, 130, "Your Score:" , GREEN);
                char scoreNum[2];
                sprintf(scoreNum, "%d", currentAppState.foodEaten);
                drawString(110, 140, scoreNum, GREEN);

                state = APP_EXIT_NODRAW;
                break;
            case APP_EXIT_NODRAW:
                // TA-TODO: Check for a button press here to go back to the start screen

                if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
                    drawStartScreen();
                    state = START;
                }
                break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
